from pathlib import Path
from itingen.cli import main
import re
import os

def test_nz_trip_regression_david():
    """
    Regression test for NZ trip output (David's itinerary).
    Compares the output of itingen with the original scaffold output.
    """
    # Define paths - use fixture by default, allow env var override for local comparisons
    scaffold_output_path = Path(os.getenv(
        "ITINGEN_NZ_BASELINE_PATH", 
        Path(__file__).parent.parent / "fixtures" / "regression" / "nz_baseline_david.md"
    ))
    output_dir = Path("output/regression_test")
    itingen_output_path = output_dir / "nz_2026" / "david" / "output_0.md"

    # 1. Run itingen generate
    # Note: We use nz_2026 which we created from scaffold data
    result = main([
        "generate",
        "--trip", "nz_2026",
        "--person", "david",
        "--format", "markdown",
        "--output-dir", str(output_dir)
    ])
    
    assert result == 0
    assert itingen_output_path.exists()

    # 2. Read outputs
    with open(scaffold_output_path, "r", encoding="utf-8") as f:
        scaffold_text = f.read()
    
    with open(itingen_output_path, "r", encoding="utf-8") as f:
        itingen_text = f.read()

    # 3. Basic Comparisons
    # Count events (using "## " as a proxy for event headers in itingen, or "### Event:" in sources)
    # Both scaffold and itingen use "## YYYY-MM-DD" for days and bullets for events.
    # Compare time-based events (exclude wake/sleep markers for consistency)

    scaffold_events = re.findall(r"^- \*\*(\d{2}:\d{2}|Wake up|Go to sleep)", scaffold_text, re.MULTILINE)
    # itingen also uses "- **" for events, wake up, and sleep markers
    itingen_events = re.findall(r"^- \*\*(\d{2}:\d{2}|Wake up|Go to sleep)", itingen_text, re.MULTILINE)

    print(f"Scaffold events/markers found: {len(scaffold_events)}")
    print(f"itingen events/markers found: {len(itingen_events)}")

    # 4. Check for key missing features in itingen output
    missing_features = []
    
    if "Emotional triggers" not in itingen_text:
        missing_features.append("Emotional annotations")
    
    if "Transition logistics" not in itingen_text:
        # itingen has "### Travel To" which is a subset, but scaffold has more descriptive "Transition logistics"
        missing_features.append("Descriptive Transition logistics")
        
    if "Plan to wrap this up by" not in itingen_text:
        missing_features.append("Wrap-up timing")
        
    if "Wake up" not in itingen_text:
        missing_features.append("Wake up markers")
        
    if "Go to sleep" not in itingen_text:
        missing_features.append("Sleep markers")

    if missing_features:
        print("\nDetected Gaps in itingen output:")
        for feature in missing_features:
            print(f"- {feature}")

    # For now, we don't fail the test on these gaps, as they are "identified" for the next phase.
    # But we want to ensure the event count is at least comparable.
    # Compare time-based events (those with HH:MM timestamps)
    scaffold_real_events = [e for e in scaffold_events if ":" in e] # simplified check for HH:MM
    itingen_real_events = [e for e in itingen_events if ":" in e] # simplified check for HH:MM

    assert len(itingen_real_events) > 0, "No events generated by itingen"

    # Just a sanity check that we are in the same ballpark (within 10 events)
    assert abs(len(itingen_real_events) - len(scaffold_real_events)) < 10, "Significant mismatch in event count"

if __name__ == "__main__":
    test_nz_trip_regression_david()
