"""Event domain model for trip itinerary events.

AIDEV-NOTE: Events represent time-bound activities in a trip itinerary.
They are parsed from Markdown files and enriched through the pipeline.
"""

from typing import List, Optional
from pydantic import BaseModel, Field, ConfigDict

class Event(BaseModel):
    """Represents a single activity, appointment, or occurrence in a trip itinerary.
    
    Events are the primary unit of work in the itinerary system. They capture
    all information about a specific activity, including when and where it occurs,
    who participates, and any dependencies or constraints.
    
    The model uses `extra="allow"` to capture additional fields from Markdown
    sources, enabling extensibility without breaking changes.
    """
    
    model_config = ConfigDict(extra="allow")

    # Core identification
    event_heading: Optional[str] = Field(None, description="Human-readable title of the event")
    kind: Optional[str] = Field(None, description="Type/category of event (e.g., 'flight', 'lodging', 'activity')")
    location: Optional[str] = Field(None, description="Where the event takes place")
    
    # Participation and dependencies
    who: List[str] = Field(default_factory=list, description="List of travelers participating in this event")
    depends_on: List[str] = Field(default_factory=list, description="Other events this event depends on")
    
    # Venue reference
    venue_id: Optional[str] = Field(None, description="Reference to a Venue object")
    
    # Timing information
    timezone: Optional[str] = Field(None, description="Timezone identifier (e.g., 'Pacific/Auckland')")
    time_utc: Optional[str] = Field(None, description="Event time in UTC (ISO 8601 format)")
    
    # Scheduling constraints
    coordination_point: Optional[bool] = Field(None, description="Marks events requiring traveler coordination")
    hard_stop: Optional[bool] = Field(None, description="Events with strict timing that cannot be delayed")
    inferred: Optional[bool] = Field(None, description="Events generated by the system vs explicitly defined")
    
    # Content
    description: Optional[str] = Field(None, description="Detailed description of the event")
    travel_to: Optional[str] = Field(None, description="Travel instructions to reach this event")
    
    # Raw data from ingest might include other fields
    # we allow extra for now to capture all Markdown key-values
